# Allocate more memory to the Gradle daemon.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# Enable AndroidX and Jetifier (for compatibility with old libraries).
android.useAndroidX=true
android.enableJetifier=true

# Ensure Gradle uses the correct Java 11 installation path.
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.24.8-hotspot

# Optimize Gradle builds.
org.gradle.parallel=true
org.gradle.configureondemand=true

#org.gradle.jvmargs=-Xmx4G
#android.useAndroidX=true
#android.enableJetifier=true
#org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-11.0.24.8-hotspot
#
