// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXMLuoViRn5afKpQcPX0D4hQEzFjDATUs',
    appId: '1:574675903576:web:c6bc90a4fce5340641562d',
    messagingSenderId: '574675903576',
    projectId: 'gyanbuddy-ae92b',
    authDomain: 'gyanbuddy-ae92b.firebaseapp.skn',
    storageBucket: 'gyanbuddy-ae92b.appspot.skn',
    measurementId: 'G-ED71GEWKRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5zhH6aRhsrnjneJ_xNX9364JyIqIMofg',
    appId: '1:574675903576:android:427e512a8a660aa441562d',
    messagingSenderId: '574675903576',
    projectId: 'gyanbuddy-ae92b',
    storageBucket: 'gyanbuddy-ae92b.appspot.skn',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoDv-hftrCCEAXTrUwFK-OuPgpVRoIcas',
    appId: '1:574675903576:ios:06b8c9ea975e99d641562d',
    messagingSenderId: '574675903576',
    projectId: 'gyanbuddy-ae92b',
    storageBucket: 'gyanbuddy-ae92b.appspot.skn',
    iosBundleId: 'skn.gyan.buddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoDv-hftrCCEAXTrUwFK-OuPgpVRoIcas',
    appId: '1:574675903576:ios:06b8c9ea975e99d641562d',
    messagingSenderId: '574675903576',
    projectId: 'gyanbuddy-ae92b',
    storageBucket: 'gyanbuddy-ae92b.appspot.skn',
    iosBundleId: 'skn.gyan.buddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXMLuoViRn5afKpQcPX0D4hQEzFjDATUs',
    appId: '1:574675903576:web:4d7df584a70a78c241562d',
    messagingSenderId: '574675903576',
    projectId: 'gyanbuddy-ae92b',
    authDomain: 'gyanbuddy-ae92b.firebaseapp.skn',
    storageBucket: 'gyanbuddy-ae92b.appspot.skn',
    measurementId: 'G-KJ4GV4KD0T',
  );
}
